version: '3'

services:
  backend:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: "ericsgear/marketplaceapi"
    ports:
      - "3002"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "ericsgear/marketplacereact"
    ports:
      - "80:3000"
    links:
      - "backend"
