FROM node as build-stage

ENV PORT=3000

RUN npm install -g ts-node typescript

WORKDIR /appmarketplace
COPY package.json . 
RUN npm run build
EXPOSE ${PORT}
CMD ["npm", "start"]


FROM nginx as prod-stage
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]