version: '3'

services:
  backend:
    env_file:
        "./client/client.env"
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: "ericsgear/marketplaceapi"
    ports:
      - "3002:3002"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "ericsgear/marketplacereact"
    ports:
      - "3000:3000"
    links:
      - "backend"
